trigger: none

stages:
  - stage: SemVer
    pool: 
      vmImage: 'ubuntu-20.04'
    jobs:
      - job: Versioning
        steps:
          - checkout: self
            persistCredentials: true
          
          - script: |
              mkdir $(Pipeline.Workspace)/downloads
              cd $(Pipeline.Workspace)/downloads
              wget https://github.com/GitTools/GitVersion/releases/download/5.5.1/gitversion-ubuntu.18.04-x64-5.5.1.tar.gz -O gitversion.tar.gz
              tar xvf gitversion.tar.gz
              rm gitversion.tar.gz
            displayName: 'Download GitVersion'

          - script: |
              git fetch --unshallow
              cd $(Build.SourcesDirectory)
              ls
              $(Pipeline.Workspace)/downloads/gitversion $(Build.SourcesDirectory)/GitVersion.yml
            displayName: Verify gitversion

          - script: |
              export tag=$($(Pipeline.Workspace)/downloads/gitversion $(Pipeline.Workspace)/config GitVersion.yml | jq -r '.FullSemVer' | sed 's/+/_/g')
              echo "##vso[task.setvariable variable=tag]$tag"
            displayName: 'Set tag variable'

          - script: |
              git tag az$(tag)
              git push origin --tags
            displayName: add and push tag

          - script: |
              rm -rf $(Pipeline.Workspace)/downloads
            displayName: 'Cleanup GitVersion'
            condition: always()