trigger: none

parameters:
- name: environment
  displayName: ambiente destino
  default: dev
  values: ['dev', 'uat']


resources:
  repositories:
  - repository: myTemplates # Alias for the repository
    type: github
    name: Faridlpz/CICD # Repository name in the format Organization/Repository
    ref: main
    endpoint: Faridlpz

stages:  
  - stage: Microservice
    pool:
        vmImage: 'ubuntu-latest'
    jobs:
      - job: Helm_templates
        steps:
          - template: templates/acr-template.yml
            parameters:
              environment: ${{ parameters.environment }}
          - template: templates/aks-template.yml
            parameters:
              environment: ${{ parameters.environment }}