trigger: none

parameters:
- name: environment
  displayName: ambiente destino
  default: dev
  values: ['dev', 'uat']


resources:
  repositories:
  - repository: myTemplates # Alias for the repository
    type: github
    name: InsertValue # Repository name in the format Organization/Repository
    ref: main
    endpoint: InsertValue

stages:  
  - stage: Microservice
    pool:
        vmImage: 'ubuntu-latest'
    jobs:
      - job: Helm_templates
        steps:
          - template: Azure_devops/aks_newman/templates/aks-template.yml@myTemplates
            parameters:
              environment: ${{ parameters.environment }}
          - task: HelmInstaller@1
            inputs:
              helmVersionToInstall: 'latest'
          - script: helm package microservice
          - task: HelmDeploy@0
            inputs:
              connectionType: Kubernetes service connectionType
              KubernetesServiceEndpoint: InsertConnection
              command: 'upgrade'
              chartType: 'FilePath'
              chartPath: 'microservice/microservice-0.1.0.tgz'
              releaseName: 'Myreponame'
              overrideValues: 'values-${{ parameters.environment }}.yaml'
              arguments: '--output-dir $(Build.ArtifactStagingDirectory)/rendered'