# Use an official Python runtime as the base image
FROM python:3.7-slim

# Set the working directory in the container (optional)
WORKDIR /app

# The ENTRYPOINT sets the command to be run when the container starts.
# This entry point allows you to run arbitrary Python commands within the container.
ENTRYPOINT ["python"]