apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.containers.name }}
        image: "{{ .Values.containers.image }}:{{ .Values.containers.tag }}"
        ports:
        - containerPort: {{ .Values.containers.port }}
        env:
        - name: {{ .Values.configmap.data.database_url }}
          valueFrom:
            configMapKeyRef:
              name: example-config
              key: database_url
        - name: {{ .Values.configmap.data.debug_mode }}
          valueFrom:
            configMapKeyRef:
              name: example-config
              key: debug_mode